version: "3.1"

services:
  elasticsearch:
    image: elasticsearch:7.16.1
    restart: unless-stopped
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cluster/health || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3

  logstash:
    image: logstash:7.16.1
    restart: unless-stopped
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./logstash/pipeline/logstash-go.config:/usr/share/logstash/pipeline/logstash-go.config
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    command: logstash -f /usr/share/logstash/pipeline/*.config

  kibana:
    image: kibana:7.16.1
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
