version: "3.1"

services:
    filebeat:
        image: docker.elastic.co/beats/filebeat:6.5.1
        volumes:
            - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./go.log:/logs/go.log