// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"database/sql"
)

type AccountFavoriteActress struct {
	ID        string
	ActressID sql.NullInt64
	AccountID int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Actress struct {
	ID           int64
	Name         sql.NullString
	Romanization sql.NullString
	Detail       sql.NullString
	Preview      sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type ActressFace struct {
	ID        int64
	Token     sql.NullString
	Preview   sql.NullString
	ActressID sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	TokenSet  sql.NullString
	Status    sql.NullInt16
}
